DjangoWebProject1/DjangoWebProject1/DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings


urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('videopost/', views.videopost,name='videopost'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Войти',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('otziv/',views.otziv,name='otziv'),
    path('admin/', admin.site.urls),
    path('registration/', views. registration, name= 'registration'),
    path('blog/', views.blog, name='blog'),
    path('newpost/', views.newpost, name='newpost'),
    path('blogpost/<int:parametr>/', views.blogpost, name='blogpost'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= staticfiles_urlpatterns()

DjangoWebProject1/DjangoWebProject1/app/forms.py
"""
Definition of forms.
"""
from .models import Blog
from django.db import models
from .models import Comment
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Пароль"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))
class otzivform(forms.Form):
    name=forms.CharField(label='Ваше имя', min_length=2, max_length=100)
    city=forms.CharField(label='Ваш город', min_length=2, max_length=100)
    purchases=forms.BooleanField(label='Совершали покупки?',
                                 required=False)
    grade=forms.ChoiceField(label="Оцените удобство сайта от 1 до 5",
                            choices=(('1','1'),
                                     ('2','2'),
                                     ('3','3'),
                                     ('4','4'),
                                     ('5','5')),initial=1)
    message=forms.CharField(label='Отзыв',
                            widget=forms.Textarea(attrs={'rows':12,'cols':20}))
class CommentForm (forms.ModelForm):

    class Meta:
        
        model = Comment # используемая модель

        fields = ('text',) # требуется заполнить только поле text

        labels = {'text': "Комментарий"} # метка к полю формы text
class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = {'title', 'description', 'content','image',}
        labels = {'title': "Заголовок",'description':"Краткое содержание",'content':"Полное содержание",'image':"Картинка"}

DjangoWebProject1/DjangoWebProject1/app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>
<div>
    <p class="text">Мы рады предложить вам широкий ассортимент качественных строительных и отделочных материалов от проверенных производителей по доступным ценам. С нами вы сможете создать уютный и комфортный дом своей мечты!</p>
</div>
<div class="ramka">
<ol class="text">
    <li>Основные категории товаров:</li>
    <li>Строительные материалы: блоки, гипсокартон, сухие строительные смеси, утеплители, гидроизоляционные и пароизоляционные материалы, метизы, строительные инструменты и многое другое.</li>
    <li>Отделочные материалы: обои, ламинат, керамическая плитка, паркет, краски, декоративные штукатурки, напольные покрытия, плинтусы, карнизы и другие элементы декора.</li>
    <li>Сантехника: ванны, унитазы, смесители, раковины, душевые кабины, водонагреватели, полотенцесушители и аксессуары для ванной комнаты.</li>
    <li>Электротовары: кабель, провод, электроустановочные изделия, щиты, счетчики, стабилизаторы напряжения, энергосберегающие лампы и другие товары для электромонтажа.</li>
    <li>Крепежные изделия: дюбели, анкеры, болты, гайки, шайбы, саморезы, гвозди и другие крепежи.</li>
</ol>
</div>
<div>
    <p class="text">
        Присоединяйтесь к числу наших довольных клиентов и делайте выгодные покупки в нашем интернет-магазине стройматериалов! Удачного ремонта и приятных покупок!
    </p>
</div>


{% endblock %}

DjangoWebProject1/DjangoWebProject1/app/templates/app/blog.html
{% extends "app/layout.html" %}
{% block content %}
<h2>{{ title }}</h2> <br />
{% for post in posts %}
<hr/>
<div class="">
<h2> {{post.title}} </h2>
<h4> {{post.posted}} </h4>
<p> {{post.description}} </p>
<p><a href="{% url 'blogpost' parametr=post.id %}"> Читать далее </a> </p>
</div>
{% endfor %}
{% endblock %}

DjangoWebProject1/DjangoWebProject1/app/templates/app/blogpost.html
{% extends "app/layout.html" %}

{% block content %}

<h2> {{post_1.title}} </h2>

{% if post_1.image and post_1.image.url != '/media/temp.jpeg' %}
<img src="{{ post_1.image.url }}" alt=" Картинка статьи блога" width="200" />
{% endif %}

<p> {{post_1.content|linebreaksbr}} </p>      {# вывод текста по абзацам#}
<p><a href="{% url 'blog' %}"> Назад</a> </p>
{% if user.is_authenticated %}

<h3>Добавить комментарий</h3>

<form method="POST" >{% csrf_token %} {# защита от атак CSRF#}

<div>

{{form.as_p}}

<button type="submit" class="save btn btn-default" > Отправить комментарий </button>

</div>

</form>

{% else %}

<h3> Для добавления своего комментария, пожалуйста, авторизуйтесь </h3>

{% endif %}
{% for comment in comments %}

<hr/>

<h7> {{comment.created_at}} </h7>

<h5> {{comment.user}} </h5>

<p> {{comment.text|linebreaksbr}} </p>

{% endfor %}
{% endblock %}

DjangoWebProject1/DjangoWebProject1/app/templates/app/contact.html
{% extends "app/layout.html" %}
{% load staticfiles %}
{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>


<ul>
    <li><a href="https://www.псковскийкирпичныйзавод.рф/"><img class="kartinka" src="{% static 'app/content/pks.png ' %}" alt="Logo 1"/>Производитель кирпича</a></li>
    <li><a href="https://kvazar.ltd/"><img class="kartinka" src="{% static 'app/content/kvaz.jpg ' %}" alt="Logo 2"/>Производитель мебели</a></li>
    <li><a href="https://sudomawood.ru/about-company/"><img class="kartinka" src="{% static 'app/content/sudoma.jpg ' %}" alt="Logo 3"/>Лесозавод «Судома»</a></li>
</ul>

{% endblock %}

DjangoWebProject1/DjangoWebProject1/app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}
<div class="jumbotron">
    <h1>СтройМаг</h1>
</div>

<div class="row">
    <div class="col-md-4">

    </div>
    <div class="col-md-4">

    </div>
    <div class="col-md-4">


    </div>
</div>
</body>
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">

    <ol class="carousel-indicators">

        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>

        <li data-target="#myCarousel" data-slide-to="1"></li>

        <li data-target="#myCarousel" data-slide-to="2"></li>

        <li data-target="#myCarousel" data-slide-to="3"></li>

    </ol>

    <div class="carousel-inner" role="listbox">

        <div class="item active">

            <img class="img1" src="{% static 'app/content/arma.webp'%} " alt="Первый слайд" class="img-responsive" />

            <div class="carousel-caption" role="option">



            </div>

        </div>

        <div class="item">

            <img class="img1" src="{% static 'app/content/cement.webp'%}" alt="Второй слайд" class="img-responsive" />

            <div class="carousel-caption" role="option">



            </div>

        </div>

        <div class="item">

            <img class="img1"src=" {% static 'app/content/kirpich.jpg'%} " alt="Третий слайд" class="img-responsive" />

            <div class="carousel-caption" role="option">



            </div>

        </div>

    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">

        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>

        <span class="sr-only">Previous</span>

    </a>

    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">

        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

        <span class="sr-only">Next</span>

    </a>

</div>

{% endblock %}

DjangoWebProject1/DjangoWebProject1/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - интернет-магазина СтройМаг</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"> <img class="kar" src="{% static 'app/content/1.png' %}" alt="logo" /> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'otziv' %}">Обратная связь</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавить статью</a></li>
                    {% endif %}
                    {% if not user.is_authenticated %}
                    <li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
                {% include 'app/loginpartial.html' %}

            </div>
        </div>
    </div>

    <div class="container body-content">
        {% block content %}{% endblock %}

    </div>


    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
    <hr />
    <footer>
        <p>&copy; {{ year }} - интернет-магазина СтройМаг</p>
    </footer>
    {% block scripts %}{% endblock %}




</html>

DjangoWebProject1/DjangoWebProject1/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Для входа в систему используйте локальную учетную запись.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Логин</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста, введите правильные логин и пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

DjangoWebProject1/DjangoWebProject1/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Здравствуйте {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Войти</a></li>
</ul>

{% endif %}

DjangoWebProject1/DjangoWebProject1/app/templates/app/newpost.html
{% extends "app/layout.html" %}
{% block content %}

<h3>Добавить статью</h3>
<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    <div>
        {{ blogform.as_p}}
        <button type="submit" class="save btn btn-default"> Сохранить статью</button>

    </div>
</form>
{% endblock %}

DjangoWebProject1/DjangoWebProject1/app/templates/app/pool.html
{% extends "app/layout.html"%}
{% block content %}
{% if form != None %}

<br> <h2>Оставте отзыв</h2><br>

<div>
    <form method="post">
        {% csrf_token %}
        <label for ="{{form.name.id_for_label}}">{{ form.name.label}}</label>
        {{ form.name}}<br><br>
        <label for ="{{form.city.id_for_label}}">{{ form.city.label}}</label>
        {{ form.city}}<br><br>
        <label for ="{{form.purchases.id_for_label}}">{{ form.purchases.label}}</label>
        {{ form.purchases}}<br><br>
        <label for ="{{form.grade.id_for_label}}">{{ form.grade.label}}</label>
        {{ form.grade}}<br><br>
        <label for ="{{form.message.id_for_label}}">{{ form.message.label}}</label>
        {{ form.message}}<br><br>
        <input type="submit" id="knop" value="Отправить">
 
    </form>

</div>
<script>
$(document).ready(function() {
 $("#knop").hover(function() {
 $(this).css("color", "#ff0000");
 }, function() {
 $(this).css("color", "#000000");
 });

$("#id_name").hover(function() {
  $("#id_name").focus(function() {
    $(this).css('background-color', '#b3e5fc');
});
  $("#id_name").blur(function() {
    $(this).css('background-color', 'white');
});
});
$("#id_city").hover(function() {
  $("#id_city").focus(function() {
    $(this).css('background-color', '#b3e5fc');
});
  $("#id_city").blur(function() {
    $(this).css('background-color', 'white');
});
});
$("#id_message").hover(function() {
  $("#id_message").focus(function() {
    $(this).css('background-color', '#b3e5fc');
});
  $("#id_message").blur(function() {
    $(this).css('background-color', 'white');
});
});
});
</script>
{% else %}
<br><h2>Спасибо за отзыв!</h2>
<h3>Вы отправили следующее</h3>
<ul>
    <li><span>Имя:</span>{{data.name}}</li>
    <li><span>Город:</span>{{data.city}}</li>
    <li><span>Покупки:</span>{{data.purchases}}</li>
    <li><span>Оценка:</span>{{data.grade}}</li>
    <li><span>Отзыв:</span>{{data.message}}</li>
</ul>
{% endif %}
{% endblock %}

DjangoWebProject1/DjangoWebProject1/app/templates/app/registration.html
{% extends "app/layout.html" %}

{% block content %}

<h2>Регистрация пользователя</h2>

<form method="POST">
    {% csrf_token %}

    <div>

        {{ regform.as_p}}

        <button type="submit" class="save btn btn-default"> Зарегистрировать </button>

    </div>

</form>

{% endblock %}

DjangoWebProject1/DjangoWebProject1/app/templates/app/videopost.html
{% extends "app/layout.html"%}
{% block content %}
<h1>{{title}}</h1>
<hr/>
<div>
<h2>Видео-ролик</h2>
<VIDEO src="/media/video1.mp4" controls="controls" width="400" height="300" poster="/media/video1.jpg"></VIDEO>

</div>
<div>
    <h2>Видео-ролик2</h2>
    <VIDEO src="/media/video2.mp4" controls="controls" width="400" height="300" poster="/media/video2.jpg"></VIDEO>
    
    </div>
{% endblock %}